import { ArtworkImage } from "@/types/gallery";

export const galleryImages: ArtworkImage[] = [
  {
    id: "1",
    title: "Toilette",
    artist: "Claude Monet",
    description: "getting ready",
    imagePath: "/images/gallery/toilette.jpg",
    width: 1200,
    height: 1200,
    alt: "oil painting",
  },
  {
    id: "2",
    title: "Brooklyn Bridge",
    artist: "unknown",
    description: "photo of the Brooklyn bridge",
    imagePath: "/images/gallery/brooklynBridge.png",
    width: 1200,
    height: 1200,
    alt: "digital photo",
  },
  {
    id: "3",
    title: "lilies in blue",
    artist: "Claude Monet",
    description: "lilies in their natural habitat",
    imagePath: "/images/gallery/wow.jpg",
    width: 1200,
    height: 1200,
    alt: "oil painting",
  },
  {
    id: "4",
    title: "Swords",
    artist: "unknown",
    description: "reflection of the sword",
    imagePath: "/images/gallery/sword.png",
    width: 1200,
    height: 1200,
    alt: "digital art",
  },
  {
    id: "5",
    title: "Lunch",
    artist: "Claude Monet",
    description: "lunch in summer",
    imagePath: "/images/gallery/lunch.jpg",
    width: 1200,
    height: 1200,
    alt: "oil painting",
  },
  {
    id: "6",
    title: "Lilies in Summer",
    artist: "Claude Monet",
    description: "lilies but kind of orange",
    imagePath: "/images/gallery/lilies.jpg",
    width: 1200,
    height: 1200,
    alt: "oil painting",
  },
  {
    id: "7",
    title: "Museum",
    artist: "Claude Monet",
    description: "museum in dusk",
    imagePath: "/images/gallery/museum.jpg",
    width: 1200,
    height: 1200,
    alt: "oil painting",
  },
  {
    id: "8",
    title: "leaves",
    artist: "unknown",
    description: "winter branch",
    imagePath: "/images/gallery/leaves.png",
    width: 1200,
    height: 1200,
    alt: "digital art",
  },
  {
    id: "9",
    title: "Stack of Wheat",
    artist: "Claude Monet",
    description: "just some wheat",
    imagePath: "/images/gallery/wheat.jpg",
    width: 1200,
    height: 1200,
    alt: "oil painting",
  },
];